### ISSUE TITLE
Error when content-type and accept headers are not application/json

### ISSUE THREAD

**Issue by nevenRakonic** [infinum/dox#19]
When ```content-type``` and ```accept``` headers on request are not ```application/json```, e.g. they're set to ```application/vnd.api+json``` I get a ```JSON::ParserError: 784: unexpected token``` when trying to generate documentation.

When response returns ```application/vnd.api+json``` in the headers, documentation can be generated.

**Comment by melcha** [comment]
I managed to reproduce this with a POST request example. When you don't specify content type header with `application/json`, body gets url encoded by default, because Rails doesn't understand `application/vnd+json` content type.

And Dox expects to get json body.

You can solve this by explicitly calling `to_json` on the body params, for example: 
``` ruby
post api_v1_authors_path, valid_attributes.to_json
```
Does this solve your issues?

**Comment by nevenRakonic** [comment]
@melcha Yes, that solves the issue. Thanks!
