### ISSUE TITLE
Using tags other than :dox

### ISSUE THREAD

**Issue by johnkeith** [infinum/dox#27]
Hi folks, 

This is a fantastic gem! 

I have a question on tagging specs to be used in documentation generation. Currently, I have it working as you mention in the readme, tagging specs with `:dox` and then running the output through the Dox::Formatter. 

I was wondering if we could use another tag? The reason for this is I would like to figure out how to seperate public API documentation from private, perhaps by tagging specs as `public_dox` and `private_dox`. I tried changing my tags in the specs to `private_dox` and then reconfiguring the rails_helper.rb configuration as below, but I cannot seem to get the documentation to generate. 

``` ruby
  config.after(:each, :private_dox) do |example|
    example.metadata[:request] = request
    example.metadata[:response] = response
  end
```

Does this use of different tags sound possible? And if so, any idea on what I might be missing to get this different tag working?

---

Also, this is how I am running the specs to produce the documentation:

```
bundle exec rspec spec/controllers/api/auth_controller_spec.rb -f Dox::Formatter --order defined --tag private_dox --out docs.md
```

**Comment by melcha** [comment]
Hello @johnkeith, 

thanks!

The **dox tag is mandatory**, you must use it for all tests you want to document, as the dox gem checks for the dox tag presence before writing the documentation for each example. 
Running tests without the dox tag option: 

`bundle exec rspec spec/controllers/api/v1 -f Dox::Formatter --order defined --out docs.md`

would create the same document as running it with the tag dox. The reason we put the tag dox in the command here is only to skip running all other tests when we’re generating the documentation.

---

As for the separating public API documentation from private, you should think about separating tests (and the code) by folders or files. And then running the tests like this:

`bundle exec rspec spec/controllers/api/v1/public -f Dox::Formatter --order defined --out public_docs.md`


If that’s not a good solution for you and you want to separate them by tags, you could add another tag, for example private_api or public_api, and then run: 

`bundle exec rspec spec/controllers/api/v1 -f Dox::Formatter --order defined --tag private_api --out private_docs.md `
`bundle exec rspec spec/controllers/api/v1 -f Dox::Formatter --order defined --tag dox --tag ~private_api --out public_docs.md `

You can check the tag option details [here](https://relishapp.com/rspec/rspec-core/v/3-7/docs/command-line/tag-option). _Note that in the first example we omitted the dox tag, because it's unnecessary and combining two inclusion tags would result in printing tests tagged with tag dox OR with tag private_api._

Or simply use both private_api and public_api tags:
`bundle exec rspec spec/controllers/api/v1 -f Dox::Formatter --order defined --tag private_api --out private_docs.md `
`bundle exec rspec spec/controllers/api/v1 -f Dox::Formatter --order defined --tag public_api --out public_docs.md `

Btw, if you’re using zsh, you might have to escape the tilde: `--tag \~private_api`.

**Comment by johnkeith** [comment]
Thanks! That is exactly what we were looking for - I really appreciate the thorough explanation.

**Comment by jozefvaclavik** [comment]
> The **dox tag is mandatory**

Should be written in Readme. I spend some time figuring out why my generated file was empty. I was going through same thing: Private/Public doc.
